### ISSUE TITLE
How to get segments from an activity?

### ISSUE THREAD

**Issue by Daszczu** [danshannon/javastravav3api#115]
I do 
`List<StravaActivity> activities = strava.listAllAuthenticatedAthleteActivities();`
to get all the activities from a user and then for every activity
`List<StravaSegmentEffort> segments = activity.getSegmentEfforts();`
but there are nulls...

What I'm trying to do is get all segments which user has driven. There's only a way to get starred segments but it's not enough. Maybe there is another way?

**Comment by danshannon** [comment]
I think the issue is that the Strava API returns summaries of the activities via the strava.listAllAuthenticatedAthleteActivities() call -  which does not include the activities’ segmentEfforts in the returned list. See https://strava.github.io/api/v3/activities/

You will need to do something like
List<StravaSegmentEffort> efforts = strava.getActivity(activity.getId(), true).getSegmentEfforts();
List<StravaSegment> segments = new ArrayList<StravaSegment>();
for (StravaSegmentEffort effort : efforts) {
segments.add(effort.getSegment());
}

for each activity

Also – that gets you a list of segments, but it will contain duplicates

Also – if you have a lot of activities on Strava, and/or they contain a lot of efforts, this will likely result in a very large number of calls to the Strava API

I hope this helps!

Dan

**Comment by Daszczu** [comment]
Thank you, there's a lot of API calls but I can manage.
There's one thing.
`StravaSegmentLeaderboard leaderBoard = strava.getAllSegmentLeaderboard(segment.getId());
List<StravaSegmentLeaderboardEntry> entries = leaderBoard.getEntries();`
One segment returned: 

> {"message":"Record Not Found","errors":[]} 
> INFO  javastrava.api.v3.rest.util.RetrofitErrorHandler - 404 Not Found : StravaResponse [message=Record Not Found, errors=[]]

and when I entered manually the segment url there is an info:

> This segment has been flagged as hazardous.

Then I click 'proceed' and leaderboard is shown. 
Is there any way I could accept hazardous segments in the API?

**Comment by danshannon** [comment]
I don't think there is a way around the hazardous segment issue you describe below - it's a restriction by Strava 

Sent from my iPhone

On 12 Apr 2016, at 3:14 AM, Daszczu <notifications@github.com> wrote:

Thank you, there's a lot of API calls but I can manage.
There's one thing.
StravaSegmentLeaderboard leaderBoard = strava.getAllSegmentLeaderboard(segment.getId());
List<StravaSegmentLeaderboardEntry> entries = leaderBoard.getEntries();
One segment returned:

{"message":"Record Not Found","errors":[]} 
INFO javastrava.api.v3.rest.util.RetrofitErrorHandler - 404 Not Found : StravaResponse [message=Record Not Found, errors=[]]

and when I entered manually the segment url there is an info:

This segment has been flagged as hazardous.

Then I click 'proceed' and leaderboard is shown. 
Is there any way I could accept hazardous segments in the API?
