### ISSUE TITLE
Externalising the ResourceBundle

### ISSUE THREAD

**Issue by bill-comer** [danshannon/javastravav3api#177]
Dan,

First off great work.

I have a working application using 1.0.0-RC2 but obviously I would like to upgrade to the latest.
However I have an issue with the properties file javastrava-application.properties

I want to deploy my application in several places, notably a test server & the live server & therefore I need multiple client_ids.

However packaging up the application in a war file containing the properties file means I have to hack in to the war & change the properties file or am I missing something?

I have looked at your code but so far I have not succeeded in modifying it to pick up an external Resources file.

Bill

**Comment by danshannon** [comment]
Bill

Sorry to be a bit slow replying! I'm aware that there are some issues with the way that you have to acquire a token, including having to shove the relevant credentials into javastrava-application.properties.

I'm thinking of providing a method to create a Token, and then an API or a Strava object, using String parameters rather than the properties file. Would that help?

Cheers

Dan

PS New version 2.0.0 on the way soon - lots of updates!

**Comment by danshannon** [comment]
See #179

**Comment by danshannon** [comment]
Should now be possible to use a token sourced externally to the app - coming in 2.0.0 soon!
